apiVersion: v1
kind: Service
metadata:
  name: party-c
spec:
  type: NodePort
  ports:
    - name: p2p
      port: 10002
      targetPort: 10002
    - name: web
      port: 10004
      targetPort: 10004
  selector:
    app: party-c
